name: Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform: ["SDL2", "GLFW3"]
        baked: ["ON", "OFF"]
        type: ["Release", "Debug"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - uses: hustcer/setup-nu@v3
      with:
        version: "0.111.0" # Don't use 0.90 here, as it would be a float number and would be converted to 0.9, you can use v0.90/0.90.0 or '0.90'

    - name: Remove unncessary dependencies from conan
      shell: nu {0}
      env: 
        PLATFORM: ${{ matrix.platform }} 
        SDL_PACKAGE: sdl/2.30.1
        GLFW_PACKAGE: glfw/3.4
      run: |
        do {
          if $env.PLATFORM == "SDL2" {
            open ./conanfile.txt 
            | str replace -a $env.GLFW_PACKAGE '' 
            | save -f ./conanfile.txt
          } else if $env.PLATFORM == "GLFW3" {
            open ./conanfile.txt 
            | str replace -a $env.SDL_PACKAGE '' 
            | save -f ./conanfile.txt
          }
        }
        
    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Install Conan dependencies
      run: |
        cmd /c "GetDependenciesConan.bat" ${{ matrix.type }} 
        
    - name: Build
      env:
          BAKED: ${{ matrix.baked }}
          TYPE: ${{ matrix.type }} 
          PLATFORM: ${{ matrix.platform }} 
      run: |
        cmd /c "Build.bat" %TYPE% %BAKED% %PLATFORM% OPENGL

    - name: Test
      run: |
        ./build/install_dir/Warfarmer/StardewEngineTest.exe

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./build/*.so # or path/to/artifact
